name: news_app
description: Test task with news.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.18.1
  http: ^0.13.5
  html: ^0.15.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true